server-port=25565
online-mode=false
motd=Hub
difficulty=peaceful
gamemode=adventure
max-players=50
view-distance=6
simulation-distance=4
spawn-protection=0
enable-command-block=true
allow-flight=true
white-list=false
enforce-whitelist=false
enable-rcon=true
rcon.password=change-this-rcon-password
rcon.port=25575
server-ip=
enforce-secure-profile=false
