# name|container|service|host|port|worldborder_center_x|worldborder_center_z|worldborder_diameter|pregeneration_radius|pregeneration_enabled|gen_map
hub|mc-hub|hub|hub|25565|0|0|1000|500|true|true
island1|mc-island1|island1|island1|25565|0|0|10000|5000|false|false
island2|mc-island2|island2|island2|25565|0|0|10000|5000|false|false
island3|mc-island3|island3|island3|25565|0|0|8000|4000|false|false
island4|mc-island4|island4|island4|25565|0|0|8000|4000|false|false
